POST http://localhost:8080/api/workSchedule
Content-Type: application/json

{
  "scheduleDate": "2020-01-11"
}

###

GET http://localhost:8080/api/workSchedule

###

GET http://localhost:8080/api/workSchedule/1

###

PUT http://localhost:8080/api/workSchedule/1
Content-Type: application/json

{
  "scheduleDate": "2021-11-11"
}

###

DELETE http://localhost:8080/api/workSchedule/1

