POST http://localhost:8080/api/workScheduling/1
Content-Type: application/json

{
  "scheduleDate": "2021-11-10",
  "from": "06:00",
  "to": "14:00",
  "location": "Hauptplatz"
}

###

PUT http://localhost:8080/api/workScheduling/1
Content-Type: application/json

{
  "from": "07:00"

}