POST http://localhost:8080/api/workScheduling
Content-Type: application/json

{
  "from": "06:00",
  "to": "14:00",
  "location": "Geschäft",
  "employee": {
    "id": 1
  }
}

###

GET http://localhost:8080/api/workScheduling/date/2021-12-07

###

PUT http://localhost:8080/api/workScheduling/1
Content-Type: application/json

{
  "from": "07:00"

}

###

DELETE http://localhost:8080/api/workScheduling/1